import Navigation from "./components/Navigation/Navigation"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Mi primera pagina con Next</title>
      </head>
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  )
}
